name: run test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        users: actions/checkout@v2
      - name: Setup Node
        users: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Run Tests
        run: npm test
